import React from "react";
import RestaurantNavbar from "../components/RestaurantNavbar";
import Menu from "../components/Menu";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Menu of  Milestone Grill (Toronto) OpenTable",
  description: "Generated by create next app",
};

const RestaurantMenu = () => {
  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavbar />
        <Menu />
      </div>
    </>
  );
};

export default RestaurantMenu;
