import React from "react";
import RestaurantNavbar from "../components/RestaurantNavbar";
import Menu from "../components/Menu";
import { Metadata } from "next";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient()


const fetchRestaurantMenu =async (slug:string) =>{
  const restaurant = await prisma.restaurant.findUnique({
    where:{
      slug
    },
    select:{
      items:true
    }
  })
if(!restaurant){
  throw new Error
}
return restaurant.items

}

export const metadata: Metadata = {
  title: "Menu of  Milestone Grill (Toronto) OpenTable",
  description: "Generated by create next app",
};

const RestaurantMenu = async ({params}:{params:{slug:string}}) => {
  const menu = await fetchRestaurantMenu(params.slug)
  
  
  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavbar slug={params.slug}  />
        <Menu menu={menu} />
      </div>
    </>
  );
};

export default RestaurantMenu;
