import React from "react";
import Header from "../components/Header";
import SearchSidebar from "./components/SearchSidebar";
import RestaurantCard from "./components/RestaurantCard";
import { Metadata } from "next";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const fetchRestaurantsByCity = async (city: string | undefined) => {
  const select = {
    id: true,
    name: true,
    main_image: true,
    price: true,
    cuisine: true,
    slug: true,
    location: true,
  };

  //in case someone deletes the search clause in the browser
  if (!city) {
    return prisma.restaurant.findMany({ select });
  }
  return prisma.restaurant.findMany({
    where: {
      location: {
        name: {
          equals: city.toLowerCase(),
        },
      },
    },
    select,
  });
};


const fetchLocations =async()=>{
  return prisma.location.findMany()
}


const fetchCuisines =async()=>{
   return prisma.cuisine.findMany();
}


export const metadata: Metadata = {
  title: "Search | OpenTable",
  description: "Generated by create next app",
};

const Search = async ({ searchParams }: { searchParams: { city: string } }) => {
  const restaurants = await fetchRestaurantsByCity(searchParams.city);
  const location = await fetchLocations()
  const cuisine = await fetchCuisines()

 

  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
      
          <SearchSidebar 
          locations={location}
          cuisines={cuisine}
          />

        
        <div className="w-5/6">
          {restaurants.length ? (
            <RestaurantCard restaurants={restaurants} />
          ) : (
            <p>Sorry, We Found No Restaurants in this Area</p>
          )}
        </div>
      </div>
    </>
  );
};

export default Search;
