import NavBar from "@/app/components/NavBar";
import React from "react";
import {
  Header,
  RestaurantNavbar,
  Title,
  Rating,
  Description,
  Images,
  Reviews,
  ReservationCard,
} from "./components/index";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: `Milestone Grill (Toronto) OpenTable`,
  description: "Generated by create next app",
};

const RestaurantDetails = () => {
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavbar />
        <Title />
        <Rating />
        <Description />
        <Images />
        <Reviews />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
};

export default RestaurantDetails;
